### ISSUE TITLE
Bug: competition leaderboard seems to sum up score from all attempts

### ISSUE THREAD

**Issue by mariussd** [koseprogg/codesandbox-backend#15]
![Screenshot 2021-03-29 134521](https://user-images.githubusercontent.com/23496288/112832251-56758000-9095-11eb-8a2f-e6bbd210c814.png)

**Comment by LudvigHz** [comment]
Fixed in https://github.com/koseprogg/codesandbox-backend/commit/29d8294e883658ddbfeff3c32f7bf0362bd3569b
