### ISSUE TITLE
Option to choose whether to save the submission

### ISSUE THREAD

**Issue by LudvigHz** [koseprogg/codesandbox-backend#17]
The user should be able to click a checkbox to choose whether they want to save their submission or not. As of now, the only way to do this is to log out.

<hr/>

Brukeren skal kunne klikke på en checkbox for å velge om de vil lagre innsendingen eller ikke.

**Comment by asmundh** [comment]
Altså at man kan få koden evaluert men ikke nødvendigvis at det er en tellende submission?

**Comment by LudvigHz** [comment]
> Altså at man kan få koden evaluert men ikke nødvendigvis at det er en tellende submission?

Yess!
Kanskje man bare vil teste koden sin før man havner på leaderboardet, eller bare at man ikke vil havne på leaderboardet i det hele tatt.

**Comment by asmundh** [comment]
Kul feature! Er vel også greit å implementere.
