### ISSUE TITLE
Sorter leaderboard på kode lengde eller kjøretid

### ISSUE THREAD

**Issue by kristianvld** [koseprogg/codesandbox-backend#19]
Forslag om å sortere leaderboard på enten kjøretid (altså kjappere kode gir høyere ranking på scoreboard) eller kortest kode (golf, hvor færrest brukte bokstaver per submission gir høyere ranking på leaderboardet):

Kjøretid kan gjerne være vanskelig å teste da den vil være sensitiv for om flere tester kjører samtidig, hvor mye stress serveren er under, om flere brukere submitter kode samtidig etc etc.

Å sortere på kode lengde kan gjerne være en mer stabil måte å rangere på.

https://github.com/koseprogg/codesandbox-backend/blob/0e3d179026e764700d1e540d206bc0df8e796f77/backend/controllers/submissionController.js#L43-L103

**Comment by kristianvld** [comment]
https://stackoverflow.com/questions/15471718/how-to-sort-results-by-string-length-on-mongodb#44161848

**Comment by LudvigHz** [comment]
Kult!
Vi tenkte på å kanskje gi score basert på kjøretid, men som du sier er ikke det så alt for lett.
Men korteste kode er også en morsom challenge!

**Comment by asmundh** [comment]
Kan kjøre koden flere ganger og lagre gjennomsnitt, _litt_ mer robust?

**Comment by kristianvld** [comment]
> Kan kjøre koden flere ganger og lagre gjennomsnitt, _litt_ mer robust?

Hva hvis det nettopp er sluppet en oppgave, 20 stykker prøver å løse den samtidig, selv om man kjører gjennomsnitt så vil jo alle 20 submissions kjøre tregt på grunn av mye pågang mot backend. Eventuelt hvis andre ting kjører på maskinen (backup, andre prosesser etc), vs hvis jeg submitter 03 om natten og gjerne ingenting skjer på nettsiden?

Vet dette var strategi tideligere i AlgDat før da de kjørte scoreboard med kjøretid på sine øvinger tideligere år 😅

**Comment by LudvigHz** [comment]
Det stemmer nok. Men vi kjører på en rimelig kraftig server som ikke kjører noe annet. Jeg tror ikke database requests eller lignende skal utgjøre noe særlig forskjell.

Jeg tenker vi kan prøve og se hvordan det går. Så kan vi velge litt hva vi gjør etter det😄

**Comment by kristianvld** [comment]
Btw, virke kun som  task leaderboards e sortert på tegn + kjøretid, men hovedscoreboard e ikkje det. Hoved scoreboard kunne muligens våre sortert på plassering per task. 

E gjerne vanskelig å normalisere kjøretid + kodelengde på tvers av oppgaver så foreslår heller gjerne gjennomsnitt plassering på alle oppgaver elns for å regne ut hovedscoreboard rekkefølge.

**Comment by kristianvld** [comment]
Submissions som ble send inn før kjøretid og kodelengde ble lagt til burde også by default rangeres lavest. 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/7207116/113173727-fb38be80-9249-11eb-9975-d6f324278e29.png">
Her e dag 2. Eg fikk 60 poeng før kjøretid og koelengde ble lagt til og ligge derfor automatisk øverst, og det e umulig for andre å forbedre seg og ta meg igjen her.

Eg får heller ikkje submitta min kjøretid og kodelengde ettersom eg allerede har ein score på 60 poeng, men gjerne et annet issue? Virke generelt random om submissions blir lagra når score e den samme?

**Comment by LudvigHz** [comment]
> Btw, virke kun som task leaderboards e sortert på tegn + kjøretid, men hovedscoreboard e ikkje det. Hoved scoreboard kunne muligens våre sortert på plassering per task.

Det er litt vanskelig å finne en bra plassering basert på score+kjøretid+tegn over alle oppgaver ja, så per nå tenker jeg den kan være som den er. (Du må gjerne komme med en PR om du har en god løsning :grin:).

>Eg får heller ikkje submitta min kjøretid og kodelengde ettersom eg allerede har ein score på 60 poeng, men gjerne et annet issue? Virke generelt random om submissions blir lagra når score e den samme?

Alle submissions lageres, uavhengig om det er samme kode og/eller score som tidligere. (Burde kanskje se på å ikke duplisere disse :thinking:). Men det er nok fordi queryet til scoreboardet ikke ble oppdatert etter kjøretid og tegn ble lagt til, så den henter beste submission per bruker kun basert på score og tar ikke hensyn på de nye feltene.
Så det burde absolutt sees på! :+1:

**Comment by asmundh** [comment]
Mongoose-queryen for leaderboards nå. Det er litt tricky å hente ut den submissionen som har enten best `executionTime` eller `characterCount` _og_ har beste score. Per nå tror jeg ikke den bruker datofeltet for rekkefølgen.

```
await SubmissionModel.aggregate([
    { $match: { parentTask: new ObjectId(competition.tasks[0]._id) } },
    { $match: { score: { $gt: 0 } } },
    { $sort: { score: -1, characterCount: 1, executionTime: 1 } },
    {
      $group: {
        _id: '$user',
        createdAt: { $first: '$createdAt' },
        score: { $first: '$score' },
        executionTime: { $first: '$executionTime' },
        characterCount: { $first: '$codeCharacterCount' },
      },
    },
    {
      $lookup: {
        from: 'users',
        let: { task_id: '$_id' },
        pipeline: [
          {
            $match: { $expr: { $eq: ['$_id', '$$task_id'] } },
          },
          {
            $project: {
              username: 1,
              profilePicture: 1,
              lastName: 1,
              firstName: 1,
            },
          },
        ],
        as: 'users',
      },
    },
    {
      $unwind: '$users',
    },
    { $sort: { score: -1, characterCount: 1, executionTime: 1 } },
  ]);
  ```

**Comment by LudvigHz** [comment]
Issuet med feil sort i task leaderbaord skal være løst av #29
