### ISSUE TITLE
User group by sorterer feil på task leaderboard

### ISSUE THREAD

**Issue by kristianvld** [koseprogg/codesandbox-backend#34]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/7207116/113522254-539bf300-959f-11eb-8f8c-4582d26c92c7.png">

Jeg har to submissions. En med `339` tegn og `13.56..ms` kjøretid. Jeg har også etter dette submittet en ny submission med `240` tegn og `18.81.. ms` kjøretid. Etter refreshing av scoreboard burde submission med `240` tegn vises, men virker som mongo grupperer lavest tid først. 

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/7207116/113522293-98278e80-959f-11eb-8450-b21ba7fabb3a.png">

Dette samsvarer også med andre submissions hvor jeg har merket at jeg må få en lavere kjøretid enn min forrige submission, selv om jeg har lavere tegn lengde for at scoreboard skal oppdateres.

Jeg kan derimot ikke se noe feil her i task `getTaskLeaderboard` da det virker som den sorterer riktig på først kode, så kjøretid både før gruppering og etter? Er det eventuelt en gammel versjon som kjører i produksjon?

https://github.com/koseprogg/codesandbox-backend/blob/b501003261d37a8d8a9190251484c6343f29c75e/backend/controllers/submissionController.js#L148-L164

**Comment by asmundh** [comment]
Vi har brukt et annet navn i modellen for en submission, `codeCharacterCount`, så sorteringen på `characterCount` gjorde ingenting. Det er fikset nå! :smile:
